#spring:
#  data:
#    mongodb:
#      database: filial-scheduler
#      uri: mongodb://localhost:27017

jasypt:
  encryptor:
    password: secret

github:
  user: your-github-username
  token: your-github-token

toss:
  client-key: your-client-key
  secret-key: your-secret-key

notification:
  slack:
    webhook:
      url: your-slack-webhook-url