spring:
  mail:
#    host: ENC(Mz2+M9eFGsqmIa8XrhwB2ZjrP+7zeBdZ)
#    port: ENC(StcEUTdFCzwO3w4w5I0ABQ==)
#    username: ENC(1/5Lr19WTv1Xoc90Tj5wyxSL9U5Y/Mcff6T8iMvrCkI=)
#    password: ENC(OuHq6eUkBDQVIp7VkHiVngFKy/PO/SO82Jj0iWCpr8Q=)
    host: ENC(10nUXy75uHV8EXVEeflaafNKUI3QKRRBsEY2U6AI0mc=)
    port: ENC(vkV8cbpyMR+ZU+Mmar2I6w==)
    username: ENC(j/qRdb1TvK2TehKQmvygV8sh3nEChSI6gtbeH9ewW8k=)
    password: ENC(+wJfin8tRY9ZAhIvm2eD47ePCKS3wfsC)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jasypt:
  encryptor:
    password: secret

cherhy:
  github:
    user: ENC(i6LGl21wvQYrZAc8xQxbGhCJowhCwikO)
    token: ENC(9pkIqXCizhAvV4b6PtPo8zFUs7jRV0rJlf+D/uY9Z5uWj4Pr+2Je6qNcbJTjv4jLQGBW/YNH030=)
  coolsms:
    api-key: ENC(iBWuy+yDiLz3gP8prw3uCEzfz4JKXgxuVyiyEFsQ1pA=)
    api-secret: ENC(FbnhbhK/Vb3OG4n1kTLpfpW55PxFk7ZyMvYxIEfm2GZfUknJCw6VIb81C9NC/EA9)
    from: ENC(XuplNn8gYityWKyxT71KWIfwYEL2n+1T)
  phone:
    mom: ENC(B4RfMZ3q+1yCxBhGlbPNBiH36a6VBvPK)
    dad: ENC(tLSWfKikFfgbYjuhpmVy5eINwX5+QFLu)
    girlfriend: ENC(UAyZdkWv8n407F0NIFM10uKraeGiI7l9)
  blog:
    user: ENC(vpBKPfz0+oDIhPkIdUpZE4KnLpvTtV2l)

ryu:
  email: ENC(5Nb//peqxArN7R+vGs1gDL3DXkrtFrsXWkR7I74W/KY=)

notification:
  slack:
    webhook:
      url: ENC(ZTEXznbbJGy7mn2DLim5fiU707we9UfwXzzStIjg1gXgE9hYCPs8LH2dzHZO38bQz9nEiUr8+h9xjxrSEFh+Bin6/2s8w0oPynP0kHmj7htx8fJVRrSQN+yVBWGVfHm7)

local:
  location:
    blog: ENC(T0obqknaUYIYtABDTMgr/uwwcVcDvx0m)
    filename: ENC(4jj+aDfIsS7VuWncA5dwdPD8e+R6fh0S1Sim7QAjXMs=)