name: Daily Commit Reward

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit_reward:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Count Commits
        id: count_commits
        run: echo "::set-output name=commit_count::$(git rev-list --count HEAD)"
      
      - name: Commit Check
        run: |
          commit_count=${{ steps.count_commits.outputs.commit_count }}
          if [ $commit_count -lt 3 ]; then
            echo "Not enough commits. Sending money to parents..."
            
            STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}"
            TRANSFER_AMOUNT=10000
            TARGET_STRIPE_ACCOUNT_ID=${{ secrets.TARGET_STRIPE_ACCOUNT_ID }}
            
            transfer_result=$(curl -X POST "https://api.stripe.com/v1/transfers" \
              -u $STRIPE_SECRET_KEY: \
              -d amount=$TRANSFER_AMOUNT \
              -d currency=krw \
              -d destination=TARGET_STRIPE_ACCOUNT_ID)
            
            if [[ $transfer_result == *"error"* ]]; then
              echo "Error occurred while transferring money."
              exit 1
            else
              echo "Money transferred successfully!"
            fi
          else
            echo "Commit goal achieved!"
          fi
